services:
  user-service-tests:
    build:
      context: ./user-service
      dockerfile: Dockerfile.test

  api-gateway-tests:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile.test
    depends_on:
      - user-service-tests

  post-service-tests:
    build:
      context: .
      dockerfile: post-service/Dockerfile.test
