services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=3560b72deb95e4162e602f3c60c1038536ff177346c7e0c903014a66b485dc4d
      - USER_SERVICE_URL=http://user-service:5001
      - POST_SERVICE_GRPC=post-service:50051
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET_KEY=3560b72deb95e4162e602f3c60c1038536ff177346c7e0c903014a66b485dc4d
      - DATABASE_URL=postgresql://postgres:postgres@user-db:5432/users
    depends_on:
      user-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

  post-service:
    build:
      context: .
      dockerfile: post-service/Dockerfile
    container_name: post-service
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@post-db:5432/posts
    volumes:
      - ./proto:/app/proto
    depends_on:
      post-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

  user-db:
    image: postgres:14-alpine
    container_name: user-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  post-db:
    image: postgres:14-alpine
    container_name: post-db
    volumes:
      - post_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=posts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - app-network
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  post_postgres_data: